"""Add Bonus Features schema

Revision ID: d2867e5387da
Revises: a01431b7a8d1
Create Date: 2026-08-24 19:19:55.032564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2867e5387da'
down_revision: Union[str, Sequence[str], None] = 'a01431b7a8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_executions', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('parent_job_id', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('shard_key', sa.String(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'jobs', ['parent_job_id'], ['id'], ondelete='SET NULL')
    op.add_column('projects', sa.Column('webhook_url', sa.String(), nullable=True))
    op.add_column('queues', sa.Column('shard_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('queues', 'shard_key')
    op.drop_column('projects', 'webhook_url')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'shard_key')
    op.drop_column('jobs', 'parent_job_id')
    op.drop_column('job_executions', 'ai_summary')
    # ### end Alembic commands ###
